### PR TITLE
Add requestor module as dependencies and many other things

### PR DESCRIPTION
**Pull request by p4535992**
@OhhLoz  I have rewritten the code in a way that I think is more "open" in the sense that it allows me to more easily add additional features, I have also removed some hooks by relying on Zhell's very well done "requestor" module that I hope to use in other ways later.

Take a look at it, do some testing and let me know.

### CODE REVIEW

**Comment by p4535992** [comment]
Using requestor probably solved this issue https://github.com/OhhLoz/Harvester/issues/34 too

**Comment by OhhLoz** [comment]
I must have completely missed this my apologies, I'll take a look asap. Thank you very much, after briefly looking at requestor it looks like its good for the hacky way I implemented the X skill check button by string replacing the html directly

**Comment by OhhLoz** [comment]
Hi, I loaded up the branch to test but I can't get the module to run correctly. The errors are as follows:
image
The files exist in modules/harvester/scripts but aren't being recognised for some reason.
Its likely something I have done wrong but I wonder if you have any ideas?

**Comment by p4535992** [comment]
Did you run `npm i` and `npm run-script build`  and use the code compiled under the `dist` folder (checkout the readme) ? 
This error is usually happening if you copy the code from the `src` folder, for avoid the issue i just add ".js" as suffix to the imports on the code, but it's advisable to use the npm commands.

**Comment by OhhLoz** [comment]
I did copy the source files directly into the modules folder you're correct. My mistake, in the future I'll use npm. Thank you the js suffix works. Everything looks great thanks once again.

**Pull request merged**
